import requests
import json

# --- CONFIGURATION ---
BASE_URL = "http://localhost:8000"
BEARER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Illhc2giLCJyb2xlIjoidXNlciIsImNhblNlbGwiOnRydWUsImlhdCI6MTc2OTM3MDY5MSwiZXhwIjoxNzY5NDU3MDkxfQ.iu92G4iVxZJkkkKDxBGnga1kbm6bEqF2fRWUmVDjx50"  # <--- PROVIDE YOUR TOKEN HERE

# --- SETUP ---
headers = {
    "Authorization": f"Bearer {BEARER_TOKEN}",
    "Content-Type": "application/json"
}

def log(step, method, url, status, response):
    print(f"[{step}] {method} {url} | Status: {status}")
    try:
        print(f"Response: {json.dumps(response, indent=2)}\n")
    except:
        print(f"Response: {response}\n")

# --- VARIABLES TO CAPTURE DYNAMICALLY ---
captured_product_id = 1 
captured_order_id = 1
captured_order_item_id = 1

# --- 1. AUTHENTICATION (Tests only, does not override provided token) ---
try:
    # Register
    res = requests.post(f"{BASE_URL}/api/auth/register", json={
        "name": "Auto Tester",
        "email": f"autotest{requests.utils.quote(str(json.dumps({})))[-5:]}@example.com", # Randomize slightly
        "password": "password123"
    })
    log("1", "POST", "/api/auth/register", res.status_code, res.json())

    # Login
    res = requests.post(f"{BASE_URL}/api/auth/login", json={
        "email": "ayash@gmail.com",
        "password": "1234"
    })
    log("2", "POST", "/api/auth/login", res.status_code, res.json())

    # Profile
    res = requests.get(f"{BASE_URL}/api/auth/api/profile", headers=headers)
    log("3", "GET", "/api/auth/api/profile", res.status_code, res.json())

except Exception as e: print(f"Auth Block Error: {e}")

# --- 2. ADDRESS & PHONE ---
try:
    # Add Address
    res = requests.post(f"{BASE_URL}/api/address", headers=headers, json={
        "line1": "123 Code St", "city": "PythonCity", "state": "PY", 
        "pincode": "101010", "country": "India", "isDefault": True
    })
    log("4", "POST", "/api/address", res.status_code, res.json())

    # Get Addresses
    res = requests.get(f"{BASE_URL}/api/address", headers=headers)
    log("5", "GET", "/api/address", res.status_code, res.json())

    # Update Address
    if res.json() and isinstance(res.json(), list):
        addr_id = res.json()[0]['id']
        res = requests.put(f"{BASE_URL}/api/address", headers=headers, json={"id": addr_id, "city": "UpdatedCity"})
        log("6", "PUT", "/api/address", res.status_code, res.json())

    # Add Phone
    res = requests.post(f"{BASE_URL}/api/number", headers=headers, json={"phone": "9876543210"})
    log("7", "POST", "/api/number", res.status_code, res.json())

    # Get Phone
    res = requests.get(f"{BASE_URL}/api/number", headers=headers)
    log("8", "GET", "/api/number", res.status_code, res.json())

except Exception as e: print(f"Profile Block Error: {e}")

# --- 3. PRODUCT MANAGEMENT ---
try:
    # Add Product (Seller only)
    res = requests.post(f"{BASE_URL}/api/products", headers=headers, json={
        "name": "Auto Test Product", "price": 100, "stock": 50, "description": "Generated by script"
    })
    log("9", "POST", "/api/products", res.status_code, res.json())
    
    if res.status_code == 201:
        captured_product_id = res.json().get("product", {}).get("id")
    else:
        # Fallback if not seller: Get existing product
        products = requests.get(f"{BASE_URL}/api/products").json().get("products", [])
        if products: captured_product_id = products[0]['id']

    # Get Products (Public)
    res = requests.get(f"{BASE_URL}/api/products?page=1&limit=5")
    log("10", "GET", "/api/products", res.status_code, res.json())

    # Update Stock
    res = requests.put(f"{BASE_URL}/api/products/stock", headers=headers, json={"id": captured_product_id, "stock": 10})
    log("11", "PUT", "/api/products/stock", res.status_code, res.json())

    # Update Meta
    res = requests.put(f"{BASE_URL}/api/products/meta", headers=headers, json={"id": captured_product_id, "isFeatured": True})
    log("12", "PUT", "/api/products/meta", res.status_code, res.json())

    # Show Seller Products
    res = requests.get(f"{BASE_URL}/api/products/show", headers=headers)
    log("13", "GET", "/api/products/show", res.status_code, res.json())

except Exception as e: print(f"Product Block Error: {e}")

# --- 4. WISHLIST & CART ---
try:
    # Add to Wishlist
    res = requests.post(f"{BASE_URL}/api/wish", headers=headers, json={"productId": captured_product_id})
    log("14", "POST", "/api/wish", res.status_code, res.json())

    # Get Wishlist
    res = requests.get(f"{BASE_URL}/api/wish", headers=headers)
    log("15", "GET", "/api/wish", res.status_code, res.json())

    # Add to Cart
    res = requests.post(f"{BASE_URL}/api/cart", headers=headers, json={"productId": captured_product_id, "quantity": 2})
    log("16", "POST", "/api/cart", res.status_code, res.json())

    # Get Cart
    res = requests.get(f"{BASE_URL}/api/cart", headers=headers)
    log("17", "GET", "/api/cart", res.status_code, res.json())

except Exception as e: print(f"Cart/Wish Block Error: {e}")

# --- 5. ORDERS ---
try:
    # Place Order
    res = requests.post(f"{BASE_URL}/api/orders", headers=headers, json={})
    log("18", "POST", "/api/orders", res.status_code, res.json())
    
    if res.status_code == 201:
        captured_order_id = res.json().get("orderId")

    # Get My Orders
    res = requests.get(f"{BASE_URL}/api/orders", headers=headers)
    log("19", "GET", "/api/orders", res.status_code, res.json())

    # Get Order By ID
    res = requests.get(f"{BASE_URL}/api/orders/{captured_order_id}", headers=headers)
    order_data = res.json()
    log("20", "GET", f"/api/orders/{captured_order_id}", res.status_code, order_data)
    
    if order_data and "orderItems" in order_data and len(order_data["orderItems"]) > 0:
        captured_order_item_id = order_data["orderItems"][0]["id"]

    # Update Order Item Status (Seller)
    res = requests.put(f"{BASE_URL}/api/orders/items/{captured_order_item_id}/status", headers=headers, json={"status": "shipped"})
    log("21", "PUT", "/items/status", res.status_code, res.json())

    # Cancel Order (Only if pending, might fail if we just shipped it, but testing the request)
    res = requests.put(f"{BASE_URL}/api/orders/{captured_order_id}/cancel", headers=headers)
    log("22", "PUT", "/orders/cancel", res.status_code, res.json())

except Exception as e: print(f"Order Block Error: {e}")

# --- 6. REVIEWS & CLEANUP ---
try:
    # Add Review
    res = requests.post(f"{BASE_URL}/api/review", headers=headers, json={
        "productId": captured_product_id, "rating": 5, "comment": "Script test review"
    })
    log("23", "POST", "/api/review", res.status_code, res.json())
    
    # Remove from Cart (Cleanup test) - Add then remove
    requests.post(f"{BASE_URL}/api/cart", headers=headers, json={"productId": captured_product_id, "quantity": 1})
    res = requests.post(f"{BASE_URL}/api/cart", headers=headers, json={"productId": captured_product_id, "quantity": -100})
    log("24", "POST", "/api/cart (Remove)", res.status_code, res.json())

    # Delete Product (Seller)
    res = requests.delete(f"{BASE_URL}/api/products/{captured_product_id}", headers=headers)
    log("25", "DELETE", f"/api/products/{captured_product_id}", res.status_code, res.json())

except Exception as e: print(f"Review/Cleanup Block Error: {e}")

print("\n--- TEST EXECUTION COMPLETE ---")